
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "RCS1141:Add parameter to documentation comment.", Justification = "We are using them on summary.", Scope = "member", Target = "~M:Services.Interfaces.Repository.IInspectionRepository.GetAllByDates(Services.Objects.User,System.DateTime,System.DateTime)~System.Collections.Generic.IList{Services.Objects.Inspection}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "RCS1141:Add parameter to documentation comment.", Justification = "We are using them on summary.", Scope = "member", Target = "~M:Services.Interfaces.Service.IServiceOfInspection.GetLast(System.Int32,System.Int32)~System.Collections.Generic.IEnumerable{Services.Objects.Inspection}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "RCS1141:Add parameter to documentation comment.", Justification = "We are using them on summary.", Scope = "member", Target = "~M:Services.Interfaces.Service.IServiceOfInspection.Save(Services.Objects.Inspection)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "RCS1141:Add parameter to documentation comment.", Justification = "We are using them on summary.", Scope = "member", Target = "~M:Services.Interfaces.Service.IServiceOfInspection.Remove(Services.Objects.Inspection)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "RCS1141:Add parameter to documentation comment.", Justification = "We are using them on summary.", Scope = "member", Target = "~M:Services.Interfaces.Service.IServiceOfInspection.GetAfterDate(System.Int32,System.DateTime)~System.Collections.Generic.IEnumerable{Services.Objects.Inspection}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "RCS1141:Add parameter to documentation comment.", Justification = "We are using them on summary.", Scope = "member", Target = "~M:Services.Interfaces.Service.IServiceOfInspection.GetAll(System.Int32)~System.Collections.Generic.IEnumerable{Services.Objects.Inspection}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "RCS1141:Add parameter to documentation comment.", Justification = "We are using them on summary.", Scope = "member", Target = "~M:Services.Service.ServiceOfInspection.GetAll(System.Int32)~System.Collections.Generic.IEnumerable{Services.Objects.Inspection}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "RCS1141:Add parameter to documentation comment.", Justification = "We are using them on summary.", Scope = "member", Target = "~M:Services.Service.ServiceOfInspection.GetAfterDate(System.Int32,System.DateTime)~System.Collections.Generic.IEnumerable{Services.Objects.Inspection}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "RCS1141:Add parameter to documentation comment.", Justification = "We are using them on summary.", Scope = "member", Target = "~M:Services.Service.ServiceOfInspection.Remove(Services.Objects.Inspection)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "RCS1141:Add parameter to documentation comment.", Justification = "We are using them on summary.", Scope = "member", Target = "~M:Services.Service.ServiceOfInspection.Save(Services.Objects.Inspection)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "RCS1141:Add parameter to documentation comment.", Justification = "We are using them on summary.", Scope = "member", Target = "~M:Services.Service.ServiceOfInspection.GetLast(System.Int32,System.Int32)~System.Collections.Generic.IEnumerable{Services.Objects.Inspection}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "RCS1141:Add parameter to documentation comment.", Justification = "We are using them on summary.", Scope = "member", Target = "~M:Services.Service.ServiceOfUser.Verify(System.String,System.String)~Services.Objects.User")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "RCS1141:Add parameter to documentation comment.", Justification = "We are using them on summary.", Scope = "member", Target = "~M:Services.Service.ServiceOfUser.Find(System.Int32)~Services.Objects.User")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "RCS1141:Add parameter to documentation comment.", Justification = "We are using them on summary.", Scope = "member", Target = "~M:Services.Service.ServiceOfUser.Verify(Services.Objects.User)~Services.Objects.User")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "RCS1141:Add parameter to documentation comment.", Justification = "We are using them on summary.", Scope = "member", Target = "~M:Services.Service.ServiceOfInspection.GetLast(System.Int32,System.Int32)~System.Collections.Generic.IList{Services.Objects.Inspection}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "RCS1141:Add parameter to documentation comment.", Justification = "We are using them on summary.", Scope = "member", Target = "~M:Services.Service.ServiceOfInspection.GetAfterDate(System.Int32,System.DateTime)~System.Collections.Generic.IList{Services.Objects.Inspection}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "RCS1141:Add parameter to documentation comment.", Justification = "We are using them on summary.", Scope = "member", Target = "~M:Services.Service.ServiceOfInspection.GetAll(System.Int32)~System.Collections.Generic.IList{Services.Objects.Inspection}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "RCS1141:Add parameter to documentation comment.", Justification = "<Pending>", Scope = "member", Target = "~M:Services.Interfaces.Repository.IPlaceRepository.Find(System.Int32)~Services.Objects.Place")]

